export { default as PrivateRoute} from './common/PrivateRoute';
export { default as Navbar} from './Layout/Navbar/Navbar';
export { default as Footer} from './Layout/Footer';
export { default as Home } from './Home/Home';
export { default as Events } from './Events/Events';
export { default as Event } from './event/Event';
export { default as CommentForm } from'./event/comments/CommentForm';
export { default as Register } from './auth/Register';
export { default as Login } from './auth/Login';
export { default as CreateEvent } from './create-event/CreateEvent';
export { default as Profile } from './Profile/Profile';
export { default as CreateProfile } from './create-profile/CreateProfile';
export { default as UserProfile } from './Profile/UserProfile';
export { default as PrivacyPolicy } from './other/PrivacyPolicy';
export { default as TermsofService } from './other/TermsofService';